### ISSUE TITLE
在vscode页面切换时如何避免webview页面重新加载。

### ISSUE THREAD

**Issue by leyue** [maqi1520/vscode-extension-cnode#6]
最近也在做这块的插件开发。
想请教下，当切换vscode页面时。
vscode.window.createWebviewPanel 我可以简单的避免webview页面被重新加载。
但vscode.WebviewViewProvider 创建的左侧固定区域webview 我找不到有什么方式可以避免页面被重新加载。

**Comment by leyue** [comment]
![image](https://github.com/maqi1520/vscode-extension-cnode/assets/11764671/efd2969a-5fd7-4d7a-9ba6-c99a368d549d)

**Comment by maqi1520** [comment]
左侧不会被重新加载呀，不懂你的场景。
可以在掘金评论
